### ISSUE TITLE
browser-repl failed with ArityException 

### ISSUE THREAD

**Issue by tokomakoma123** [plexus/chestnut#108]
I've tested the latest version. the run looked fine but the browser-repl failed with ArityException.

```clj
testapp.server> (run)
Figwheel: Starting server at http://localhost:3449
Starting web server on port 10555 .
#<Server org.eclipse.jetty.server.Server@70a9c363>
testapp.server> Compiling "resources/public/js/app.js" from ["src/cljs" "env/dev/cljs"]...
Successfully compiled "resources/public/js/app.js" in 4.204 seconds.[0m
notifying browser that file changed:  resources/public/js/app.js
notifying browser that file changed:  resources/public/js/out/goog/deps.js
notifying browser that file changed:  /testapp/core.js
notifying browser that file changed:  /testapp/main.js

testapp.server> 
testapp.server> 
testapp.server> (browser-repl)
<< Started Weasel server on ws://0.0.0.0:9001 >>
Type `:cljs/quit` to stop the ClojureScript REPL
ArityException Wrong number of args (3) passed to: piggieback/cljs-eval  clojure.lang.AFn.throwArity (AFn.java:429)
```

**Comment by plexus** [comment]
Seems the code we have to set the namespace after launching weasel no longer works. `cljs-eval` now takes an extra argument and I'm not sure what to pass it.

@tomjakubowski @swannodette is there a better/correct way to do this? we basically want the clojurescript repl to open in a certain namespace straight away. This is what we've done up to now

``` clojure
(defn browser-repl []
  (let [repl-env (weasel/repl-env :ip "0.0.0.0" :port 9001)]
    (piggieback/cljs-repl :repl-env repl-env)
    (piggieback/cljs-eval repl-env '(in-ns 'sesame-seed.core) {})))
```

**Comment by swannodette** [comment]
@plexus `piggieback/cljs-eval` needs to take the REPL options. The problem is that `piggieback/cljs-repl` computes this for you. However since you aren't in a normal REPL loop this just isn't going to work. Likely piggieback should probably return REPL options or provide some other means to invoke eval with REPL options set correctly. Anyhow this is @cemerick territory, nothing much to do with Weasel or ClojureScript.

**Comment by plexus** [comment]
I guess it was a hack to begin with :) does make it more user friendly though, so I'd be sad to drop this "feature". But I'll disable it for now, unless @cemerick has any suggestions.
