### ISSUE TITLE
Lighttable and external browser, kind of works.

### ISSUE THREAD

**Issue by jmatsushita** [plexus/chestnut#112]
Hi,

I'm able to make the Lighttable workflow work with the integrated browser but get strange results when attempting to use it with the external browser.

When I embed the script code from LT into the resources/index.html template, the server restarts correctly but:
 * weirdly the script appears twice in the generated index.html, once with the original path and a duplicate ```<head>``` ```<script>``` tag with a slightly different path:

```
  <head>
    <link type="text/css" rel="stylesheet" href="css/style.css">
    <script src="http://localhost:53610/socket.io/lighttable/ws.js" id="lt_ws" type="text/javascript"></script>
    <script src="http://localhost:53610/socket.io/socket.io.js" type="text/javascript"></script>
  </head>
```

 * Also there are a number of errors in the external browser (chrome) console:

```
core.js:63 (anonymous function) Uncaught TypeError: undefined is not a function  
socket.js:71 Figwheel: trying to open cljs reload socket
socket.js:110 Figwheel: socket connection established
websocket.js:279 WebSocket connection to 'ws://localhost:9001/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
repl.js:172 WebSocket error goog.net.WebSocket.ErrorEvent {type: "error_1", target: goog.net.WebSocket, currentTarget: goog.net.WebSocket, propagationStopped_: false, defaultPrevented: false…}
repl.js:157 Closed Websocket REPL connection
```

But!... it works and I can evaluate code with the cmd-enter shortcut inside Lighttable.

**Comment by slester** [comment]
@jmatsushita Can you confirm this happening with updated Chestnut? If not the latest on clojars, if you'd try my PR that updates Clojure and dependencies (see: https://github.com/slester/chestnut/tree/update-versions) that would be really helpful! Thanks.

**Comment by slester** [comment]
This is related to a figwheel-LightTable interdependence problem: https://github.com/bhauman/lein-figwheel/issues/119 (and @jmatsushita commented in that issue as well).

**Comment by plexus** [comment]
Looking at the upstream issue I'm assuming this can be closed. Both Lighttable and Figwheel have changed a lot in the meanwhile. If people encounter problems with the latest lighttable and Chestnut 0.9, please open a new issue.
