### ISSUE TITLE
Make server production ready

### ISSUE THREAD

**Issue by danielcompton** [plexus/chestnut#118]
There are a few optimisations that could be added to speed up production usage:

- [x] Gzip text files
- [x] Add browser caching hints

Would these be welcome in a patch?

**Comment by plexus** [comment]
Yes, please!

**Comment by manuel-uberti** [comment]
How is this going on? I am available to help (especially if tests are needed).

**Comment by danielcompton** [comment]
Hey I'm not really using Chestnut at the moment, so I haven't had time to look at this sorry. Happy for others to work on it.

**Comment by slester** [comment]
@manuel-uberti Let me know if you start working on this; otherwise, I'll probably implement it this weekend. Thanks!

**Comment by manuel-uberti** [comment]
@slester feel free to start, but you can count me in for testing if needed.

**Comment by slester** [comment]
@manuel-uberti I pushed the gzipping part to my branch https://github.com/slester/chestnut/tree/prod-mode but the browser hints is proving a bit more difficult. I'm going to work on a more robust solution, I think.

**Comment by manuel-uberti** [comment]
Good! Tomorrow I'll check it out and do some tests.

**Comment by slester** [comment]
@manuel-uberti I just updated to add browser caching hints as well on the same branch. The configuration stuff is in `:env` for each of the dev/uberjar profiles. Let me know if that breaks anything! I had to write a custom ring middleware plugin, https://github.com/slester/browser-caching -- @plexus let me know if you disapprove.

Thanks to all for testing! :)

**Comment by manuel-uberti** [comment]
This is probably due to my lack of experience, so please be patient with the newbie.

This is what I am doing:

- I cloned @slester Chestnut branch: ```git clone https://github.com/slester/chestnut/tree/prod-mode```
- I checkout to prod-mode: ```git checkout prod-mode```
- I generated the jar:
```
% lein jar
Created /home/manuel/githubs/chestnut/target/lein-template-0.8.1.jar
```
- I moved to ```target``` directory: ```cd target```
- I created a new test project: ```lein new chestnut test-chestnut```
- This is what I get: http://pastebin.com/4jDAFEHV

**Comment by slester** [comment]
@manuel-uberti after you `lein jar` you'll need to do `lein install` which will place it in your `~/.m2/` maven jar cache. Then you can `lein new chestnut` in your projects directory (or wherever). To get back the master, you'll have to delete the chestnut directory under `~/.m2`

Let me know if you need further help!

**Comment by manuel-uberti** [comment]
Thanks, worked like a charm.
```
:dependencies [[org.clojure/clojure "1.7.0"]
                         [org.clojure/clojurescript "0.0-3308" :scope "provided"]
                         [ring "1.4.0"]
                         [ring/ring-defaults "0.1.5"]
                         [slester/ring-browser-caching "0.1.0"]
                         [bk/ring-gzip "0.1.1"]
                         [compojure "1.4.0"]
                         [enlive "1.1.6"]
                         [org.omcljs/om "0.9.0"]
                         [environ "1.0.0"]]
```
```
:env {:is-dev true
         :browser-caching {"text/javascript" 0
                                       "text/html" 0}}
```

**Comment by plexus** [comment]
Doing lein jar isn't even necessary. Lein install will build the jar if it
isn't there. All of this is described in the docs BTW.

**Comment by slester** [comment]
You're right, sorry, I meant in this case he needed to `lein install` to get it in the proper place! [The relevant docs are here.](https://github.com/plexus/chestnut#local-copy)

**Comment by manuel-uberti** [comment]
Thanks for the link at the documentation. Now, is there something in particular you need me to test?

**Comment by slester** [comment]
@manuel-uberti Just that gzip compression works and that the file types you modify in the project.clj actually modify the headers. They were pretty simple changes, so mostly "does it break in normal use?" and "does it work on heroku?" are my two main concerns.

**Comment by plexus** [comment]
Please, no need to be sorry! I just thought I could add some info. I didn't
mean to sound snarky or anything.

Carry on 😊🐤🌞
