### ISSUE TITLE
Config chestnut develop environment to support source map

### ISSUE THREAD

**Issue by hung-phan** [plexus/chestnut#121]
Hi there,

Sorry, I cannot not find anywhere else to ask this question. I am trying to config chestnut developing environment to output source-map for easy debugging. But it seems like the config doesn't work.

```
(defn start-figwheel []
  (let [server (fig/start-server { :css-dirs ["resources/public/css"] })
        config {:builds [{:id "dev"
                          :source-paths ["env/dev/cljs" "src/cljs"]
                          :compiler {:output-to            "resources/public/js/app.js"
                                     :output-dir           "resources/public/js/out"
                                     :source-map           "resources/public/js/out.js.map"
                                     :source-map-timestamp true
                                     :preamble             ["react/react.min.js"]}}]
                :figwheel-server server}]
    (fig-auto/autobuild* config)))
```
It doesn't produce the source map file. Did I miss something?

And moreover, Thanks for your works with Chestnut.

**Comment by hung-phan** [comment]
The commands I run are:

```
(run)
(browser-repl)
```

**Comment by plexus** [comment]
> Sorry, I cannot not find anywhere else to ask this question.

I can only assume you didn't look at the README:

![2015-05-21-180829_669x36_scrot](https://cloud.githubusercontent.com/assets/32212/7753241/77a8c61c-ffe4-11e4-8e38-92deb85cc920.png)

To answer your question though: I do not know. I get to play around with Clojure at best once a month these days. Even though Chestnut has become quite popular there is little to no interest from the community to help me maintain it. On top of that being a beginner-level template leads to a bunch of general "how do I Clojurescript" questions popping up on the issue tracker. While I would love to answer all of these for the sake of supporting people that are starting out, I have to admit that I don't have the expertise or the time to answer these questions. I suggest you try your luck at Stackoverflow.

**Comment by hung-phan** [comment]
Thanks @plexus.
