### ISSUE TITLE
Can't create a working project with cljx enabled

### ISSUE THREAD

**Issue by gazliddon** [plexus/chestnut#128]
After creating a project with:

    lein new chestnut pogue  -- --cljx --less 
    lein deps
    lein repl

I get eventually get the error:

    Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cljx.repl-middleware/wrap-cljx in this context, compiling:(/tmp/form-init4482474082450783923
    .clj:1:2917) 

And then it just softlocks. I recorded it all here:

https://asciinema.org/a/3rr1xdh46fmqaxghdrfeey9sk

I get the same error using --snapshot as well

Without the cljx option it all works fine :)

**Comment by jcdcodes** [comment]
I just tried this with Leiningen 2.5.0 and had no trouble; repl started right up.  Then I upgraded to Leiningen 2.5.1 and now I see the same problem.

**Comment by jcdcodes** [comment]
As with #127 it looks like one just needs to add [com.keminglabs/cljx "0.6.0" :exclusions [org.clojure/clojure]] to :profiles :dev :dependencies to get things running again.  I'll try to put a PR together if you like.

**Comment by plexus** [comment]
Yeah a PR would be great. Thanks!

**Comment by pletcher** [comment]
Hey @jcdcodes, are you still working on this? I was able to patch a local version of Chestnut to generate a working template with your fix; it'd be great to have your patch in master! (Happy to help out with submitting the PR if you'd like.)
