### ISSUE TITLE
Figwheel dev server ignores project.clj

### ISSUE THREAD

**Issue by nbardy** [plexus/chestnut#133]
When launching a figwheel dev server with `(run) it uses the arguments provided in /env/dev instead of the project settings. This can cause confusion when changing the :dev profile settings in the project file has no result.

**Comment by plexus** [comment]
This has been "fixed" in the [v0.9 branch](https://github.com/plexus/chestnut/tree/v0.9), we let figwheel read the config straight from project.clj.
