### ISSUE TITLE
Doesn't work on Windows 7

### ISSUE THREAD

**Issue by helarqjsc** [plexus/chestnut#134]
When I start REPL and type `(run)`, I get the following error:
```
three-html-boxes.server=> (run)

InvalidPathException Illegal char <:> at index 2: /C:/github/three-html-boxes/resources/index.html  sun.nio.fs.WindowsPathParser.normalize (WindowsPathParser.java:182)
```
I get the same error in git bash and regular cmd. Any ideas on how to fix that?

**Comment by plexus** [comment]
closing as it's a duplicate of an existing issue.

**Comment by helarqjsc** [comment]
My bad, it is indeed the same issue as #104
