### ISSUE TITLE
Reason for `:scope "provided"` on ClojureScript dependency?

### ISSUE THREAD

**Issue by neverfox** [plexus/chestnut#137]
Is there a reason why clojurescript is `:scope "provided"` given that this isn't a library someone is going to depend on where you would normally do that?

**Comment by slester** [comment]
From [leiningen docs](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md):
>The :provided profile is used to specify dependencies that should be available during jar creation, but not propagated to other code that depends on your project. These are dependencies that the project assumes will be provided by whatever environment the jar is used in, but are needed during the development of the project. This is often used for frameworks like Hadoop that provide their own copies of certain libraries.

It seems somewhat reasonable in order to avoid having any upstream clojurescripts potentially being the wrong version. As for whether or not there'll be an upstream, it's certainly possible. Is there a particular reason this isn't desired behavior?

**Comment by neverfox** [comment]
No reason. I just didn't expect that people used Chestnut to make jars that might be deployed in a context where clojurescript would already be provided, given that I assumed it exists mainly to get people started with making clojurescript apps. That could simply be a mistaken assumption on my part.

BTW and FWIW, that doc snippet and [the maintainer of Leiningen](http://librelist.com/browser//leiningen/2014/9/7/clarifications-about-scope-in-dependencies/#32fcd639eb09c94545bec6a56c200167) suggests not using the `:scope "provided"` method but instead using the `:provided` profile as a best practice.

**Comment by plexus** [comment]
Once your jar is built clojurescript is no longer needed, all code has been
compiled to plain Javascript.

Please leave github issues for actual bugs. You can ask questions on the
chestnut forum, as mentioned in bold on top of the readme.

**Comment by neverfox** [comment]
AH, that makes sense. I wasn't aware that CLJS was treated differently from other dependencies when compiled.

As for leaving the issue here, had the answer been different, I was planning on submitting a PR. Since with was directly related to a specific code change, I assumed it belonged here. I'll "triage" (as you put it) issues in the future.
