### ISSUE TITLE
Is there a way to start the development server with a single console command?

### ISSUE THREAD

**Issue by helarqjsc** [plexus/chestnut#145]
I mean, doing this every time is a bit tedious:
```
lein repl
(run)
(browser-repl)
```

**Comment by slester** [comment]
I found this when searching: http://stackoverflow.com/questions/19682876/start-lein-repl-with-commands-from-the-terminal

Also, please don't open issues for questions. As per the README, there is a mailing list/forum for you to ask these kinds of questions on. Thanks!
