### ISSUE TITLE
clojurescript 1.7.28

### ISSUE THREAD

**Issue by tokomakoma123** [plexus/chestnut#146]
I replaced the version of clojurescript 0.0-3308 for 1.7.28 in project.clj  and the sample code in the core.cljs worked.

https://github.com/tokomakoma123/chestnut/commit/d78083174cff307ed4819151c6fc43a4c6dc47a3

**Comment by plexus** [comment]
Thanks! would you mind making a pull request?

**Comment by tokomakoma123** [comment]
No,not at all. I will make a pull request.
