### ISSUE TITLE
Evaluate function in REPL

### ISSUE THREAD

**Issue by edipofederle** [plexus/chestnut#148]
Hi,
I really don't know is this is a kind of issue or some misunderstood.

What I am doing is:

1. lein new chestnut demo
2. cd demo
3. edit src/cljs/core.clj to include a function, lets say: ```(defn hello [name] (str "Hello " name)```
4. lein repl
5. ```(in-ns 'demo.core)```
6.``` (hello "Jhon")```

```CompilerException java.lang.RuntimeException: Unable to resolve symbol: hello in this context, compiling:(/private/var/folders/rc/y5p0pv054xb20rtgwhzx5pzc0000gn/T/form-init5233994600750508423.clj:1:1)```

or even

```(+ 1 1)```

or any function...

What I missed?

Thanks in advance

**Comment by slester** [comment]
For questions like this in the future, please use http://chestnut.aren.io/ -- if it's a real issue, feel free to open one here.

You're editing ClojureScript if you're in `src/cljs/appname/core.cljs` not `src/clj/appname/core.clj` -- note the s's -- this will have to be compiled and interacted with by first doing `(run)` then `(browser-repl)` -- then you should be able to run it via the REPL.

e.g.

in your `src/cljs/demo/core.cljs`
```clojure
(defn hello [name] (str "Hello " name))
(defn hello-alert [name] (js/alert (str "Hello " name)))
```

Then back in the command line,
```
lein repl
demo.server=> (run)
demo.server=> (browser-repl) ;; go to localhost:10555
cljs.user=> (in-ns 'demo.core)
demo.core=> (hello "edipofederle")
Hello edipofederlenil
demo.core=> (hello-alert "edipofederle") ;; will show up in your browser
nil
```

**Comment by edipofederle** [comment]
Great. Thanks. And sorry for open this question here. It will not happen again.

**Comment by slester** [comment]
@edipofederle No worries! Thanks for using Chestnut!
