### ISSUE TITLE
Advertised sablono version doesn't work

### ISSUE THREAD

**Issue by p14n** [plexus/chestnut#150]
Hi,

The version of sablono advertised in the wiki doesn't work - the google closure code loads it before React . To get a working version I had to bring some dependencies up to date.  Happy to do a PR, but this is more in case someone else is struggling.

 :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "1.7.48" :scope "provided"]
                 [ring "1.4.0"]
                 [ring/ring-defaults "0.1.5"]
                 [compojure "1.4.0"]
                 [enlive "1.1.6"]
                 [org.omcljs/om "0.9.0"]
                 [environ "1.0.0"]
                 [http-kit "2.1.19"]
                 [sablono "0.3.5"]]

Cheers

**Comment by slester** [comment]
There's already an update to dependencies PR -- can you try it with those dependencies? https://github.com/slester/chestnut -- `prod-mode` branch.

**Comment by slester** [comment]
Assuming this works with updated dependencies.
