### ISSUE TITLE
Drop CLJX in favor of CLJC

### ISSUE THREAD

**Issue by plexus** [plexus/chestnut#154]
Drop the `--cljx` option to `lein new`. Provide some affordances in the base template for CLJC.

**Comment by psalaberria002** [comment]
+1

**Comment by plexus** [comment]
FWIW my current consulting contract ends at the end of the year, I intend to bring Chestnut up to date again with current practices after that.

**Comment by plexus** [comment]
CLJX has been dropped in the [v0.9 branch](https://github.com/plexus/chestnut/tree/v0.9). Adding a CLJC example isn't high priority for me, but I would accept it as a contribution.
