### ISSUE TITLE
Use figwheel for repl and ring server

### ISSUE THREAD

**Issue by plexus** [plexus/chestnut#155]
This is gonna be a big change in how you use a Chestnut project in dev mode, to the extent that I'm considering simply giving it a different name to prevent confusion.

Right now we do `lein repl`, and then have a magical `(run)` which starts figwheel and starts a ring server. With `(browser-repl)` you can switch to a Clojurescript REPL. So the end result is

* figwheel reloading of Cljs + CSS
* a ring web server
* a Clojure REPL
* a Clojurescript REPL
* all in a single process so you can access runtime state and save memory
* usable with nREPL (e.g. CIDER)

This workflow stems from before Figwheel came with its own REPL. To achieve the above we include a separate Clojurescript REPL, Weasel; and duplicate the figwheel config so we have it available to launch figwheel-sidecar (the standalone, non-leiningen version of figwheel).

We can achieve the same list of things by telling people to use `lein figwheel`, and configure figwheel with a ring-handler and nrepl-port. Connect to the nREPL port (e.g. with `cider-connect`) for a Clojure REPL, and use figwheel's `(cljs-repl)` to get a Clojurescript REPL (or just use the REPL provided by lein-figwheel).

This way we can drop the duplicated figwheel config (the ugliest bit about Chestnut right now), and drop the dependencies on figwheel-sidecar and weasel.

I'll be adding this to my stack of FOSS tasks, but if anyone wants to get to it before I manage I will make sure to reward that person with a suitable amount of appreciation and animated gifs. Oh and of course Chestnut stickers :)

**Comment by psalaberria002** [comment]
Hei!

Has any work been done in regards to this task? I am facing some issues after updating figwheel to "0.5.0-2" and clojurescript to "1.7.170".

**Comment by plexus** [comment]
I've just started working on it, however it's still in a very early state. Not recommended unless you want to help fix things.

https://github.com/plexus/chestnut/pull/160

**Comment by plexus** [comment]
This has now been implemented in the [v0.9 branch](https://github.com/plexus/chestnut/tree/v0.9). Please give it a spin if you get the chance and report any problems back.
