### ISSUE TITLE
live reloading doesn't work

### ISSUE THREAD

**Issue by tmtwd** [plexus/chestnut#158]
I have to refresh the page when changing code for this project

https://github.com/tmtwd/chess-om

I get this warning, when I change the default app-state atom

Use of undeclared Var chess-game.core/  at line 105 src/cljs/chess_game/core.cljs

**Comment by plexus** [comment]
You have a non-breaking space (U+00A0) on the last line of `core.cljs`. Clojure does not treat that as whitespace, but instead tries to find a var named <no-break space>. Take it out and your figwheel runs normally again.

**Comment by plexus** [comment]
If you can, configure your editor to make non-breaking spaces visible (in my Emacs setup they look like colored underscored). They can easily sneak into code when copy-pasting from web pages, and can be real head->desk kind of bugs to figure out.
