### ISSUE TITLE
project name "cljs" disallowed

### ISSUE THREAD

**Issue by mobileink** [plexus/chestnut#163]
I suggest you add a note to the README indicating that "cljs" will not work as a project name.

lein new chestnut cljs
cd cljs
lein repl
...
user=> (run)
Figwheel: Starting server at http://localhost:3449
Figwheel: Watching build - app
Compiling "resources/public/js/compiled/cljs.js" from ["src/cljs"]...
nil
java.lang.AssertionError: Assert failed: Circular dependency detected,  -> cljs.core -> om.dom -> cljs.core

Changing the project name to something else seems to work.

**Comment by marad** [comment]
There are much more names that can't be used (clojure, compojure, ring, environ). I'm not sure if all of them should be specified in the readme. What do you think?

**Comment by mobileink** [comment]
Maybe just some kind of warning, like "Some names (e.g. "cljs") won't work
as project names.  If you get an exception when you run "lein new chestnut
<projname>", try a different project name.

I suppose this really should be documented in leiningen.  (Maybe it is and
I just missed it.)

Nice template, BTW.  I was up and running in no time once I figured out the
problem with "cljs".

On Wed, Feb 3, 2016 at 9:15 AM, Marcin Radoszewski <notifications@github.com

**Comment by plexus** [comment]
This is a "problem" with Clojure in general, and you have similar issues in other languages. If two files define the same namespace only the one that's first in the classpath will get loaded.

I don't think this is a problem people commonly run into though, as both library and project names tend to be somewhat specific or unique. At least that's a good idea, to minimize namespace clashes. Anyway I'll add something to the FAQ. Thanks for reporting.
