### ISSUE TITLE
Please add Devcards support :)

### ISSUE THREAD

**Issue by kristianmandrup** [plexus/chestnut#164]
Template looks promising, testing it out ;)

As an alternative, perhaps the server could be using ClojureScript on Node.js?

**Comment by plexus** [comment]
Hi Kristian, 

Thanks for the suggestion, but filing this as an issue is not helpful. If you want to discuss the direction Chestnut should take in the future, and especially if you want to help making it a reality, then head to the mailing list and start a discussion there.

**Comment by kristianmandrup** [comment]
Sorry, didn't notice the mailing list. Will do ;)
