### ISSUE TITLE
Any easy way to make a chestnut project to be properly displayed shown as a github page?

### ISSUE THREAD

**Issue by thiagofm** [plexus/chestnut#165]
Hello,

So, does that feature exist? If not, I think it would be a great addition to the project. Because as soon as you run a command, you get a version of your project that could become a Github page, so you can just share your project easily.

Cheers.

**Comment by plexus** [comment]
I'm not sure what you mean by this. You can't deploy a Java server app on gh-pages.

**Comment by thiagofm** [comment]
@plexus you can generate the compiled assets + html and serve it on github pages, that's what I've meant.

**Comment by plexus** [comment]
Ok I see, but Chestnut apps have both a backend and a frontend, that's the main use case for Chestnut. Officially supporting gh-pages would be confusing as only half of your app would work. There's also not much that we can do more, you can already take the compiled assets and push them to a gh-pages branch. That's all that's needed to host on Github pages.
