### ISSUE TITLE
Escape characters being printed to REPL instead of arrow keys

### ISSUE THREAD

**Issue by vans163** [plexus/chestnut#169]
After doing (browser-repl), using arrowkeys prints the escape characters to the shell instead of the normal behavior (^[[D, etc).

Outside of (browser-repl) this does not happen, if you say CTRL+D out.

**Comment by mcomella** [comment]
This can be worked around by wrapping with `rlwrap`: `rlwrap lein repl` then the usual `(run)` & `(browser-repl)`, assuming you have `rlwrap` installed (it's available on brew).

iirc, I've seen this before outside of chestnut though so I think it's a larger issue.
