### ISSUE TITLE
Template ignoring option flags

### ISSUE THREAD

**Issue by johnboy14** [plexus/chestnut#171]
When I specify alternative options as shown below the project is still generated using the default options

`lein new chestnut chestnutdemo --http-kit --sass --reagent --vanilla`

project.clj
```
:dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/clojurescript "1.7.228" :scope "provided"]
                 [ring "1.4.0"]
                 [ring/ring-defaults "0.2.0"]
                 [bk/ring-gzip "0.1.1"]
                 [ring.middleware.logger "0.5.0"]
                 [compojure "1.5.0"]
                 [environ "1.0.2"]
                 [org.omcljs/om "1.0.0-alpha31"]]
```

**Comment by plexus** [comment]
From the README:

>Use `--` to separate these options from Leiningen's options, e.g. `lein new chestnut foo --snapshot -- --http-kit`

Recent versions of Leiningen are more picky about this
