### ISSUE TITLE
Latest Chestnut template breaks w/ figwheel 0.5.3-2

### ISSUE THREAD

**Issue by mcomella** [plexus/chestnut#174]
I recently pulled down the template again and got failures:

    user=> (browser-repl)
    Launching ClojureScript REPL for build: app
...

    Prompt will show when Figwheel connects to your application
    Failed to launch Figwheel CLJS REPL: nREPL connection found but unable to load piggieback.
    Please install https://github.com/cemerick/piggieback
    
    Exception Failed to launch Figwheel CLJS REPL: nREPL connection found but unable to load piggieback.
    Please install https://github.com/cemerick/piggieback  figwheel-sidecar.repl/eval19887/fn--19888 (repl.clj:144)

Workaround is to use figwheel 0.5.2.

**Comment by ajbisberg** [comment]
I had the same error and added these lines, seemed to work after that.
in `project.clj`
```
              :repl-options ;; Added this to enable figwheel to run
              {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}
```

**Comment by plexus** [comment]
Thanks for reporting, Chestnut 0.13.0 is out with the fix.
