### ISSUE TITLE
Can 'mount' be considered instead of 'system' as reloaded-style framework?

### ISSUE THREAD

**Issue by altV** [plexus/chestnut#184]
https://github.com/tolitius/mount as a components state management library looks way simpler, and 'just works' with tools.namespace reload as well.

(Components are defined with
```
(defstate server
  :start  ..
  :stop ..)
```
and 'mount' uses clojure compiler itself to track the correct order of components loading and stopping.)

Tools.namespace reload is like this
```
(defn go []
  (start)
  :ready)

(defn reset []
  (stop)
  (tn/refresh :after 'dev/go))
```

(Mount seems to be simpler and less java way of doing the same thing, while being also compatible with testing.)

If this looks suitable for a pull-request, I can make one within 2-3 weeks.

**Comment by plexus** [comment]
I'm aware of Mount. The relative merits of Component vs Mount have been discussed to death already elsewhere, I don't want to replay that discussion here.

Personally I prefer Component for a number of reasons. At this point with the component implementation still incomplete and in flux I don't want to add the complexity of also having to maintain a mount flag. Once a stable release of Chestnut using Component has been out for 3 to 6 months I'm willing to reopen that discussion to see if supporting both is worth the added complexity.

**Comment by altV** [comment]
got it. Can't close this ticket myself, please close it.

**Comment by plexus** [comment]
I closed it. Thanks for the suggestion!
