### ISSUE TITLE
CLJS not compiling when uberjar is called?

### ISSUE THREAD

**Issue by Qwerp-Derp** [plexus/chestnut#195]
I have a (fairly heavily modded) Chestnut project, which I'm currently using for my science project. [Here is the repo](https://github.com/Qwerp-Derp/clojure-webapp).

When I try to run `lein uberjar`, however, I'm noticing that the ClojureScript files aren't compiling properly (i.e. there's no `js` folder in `resources/public`), which therefore causes the error when I do `lein run`:

    Failed to load resource: the server responded with a status of 404 (Not Found)

I think this is a problem when I upload my project to Heroku as well, but I need to investigate further.

What's going on? I honestly have no clue.

**Comment by plexus** [comment]
Hi @Qwerp-Derp ,

Support questions belong on the mailing list, issues are for bugs and feature requests.

I get a 404 when trying to access your repo, is it private?

I would generate a new chestnut app, and then compare your project.clj with the one from the newly generated app. In particular the :uberjar profile near the bottom.

Good luck!

**Comment by Qwerp-Derp** [comment]
Oh, sorry about that (both the support question thing and the private repo thing). I thought private repositories in Github were the same as Github Gists, in the fact that anyone can view them as long as they have the link. Thanks for the advice, will ask over there instead!
