### ISSUE TITLE
'lein less auto' cant run

### ISSUE THREAD

**Issue by tkachenko1503** [plexus/chestnut#200]
Hello
Thanks for awesome lein template

I faced with problem that less compilation cant be started

I found bug in this place
```clojure
(defrecord ShellComponent [command]
  component/Lifecycle
  (start [this]
    (if-not (:running this)
      (println "Shell command:" (str/join " " command))
      (future (apply clojure.java.shell/sh command)))
    (assoc this :running true)))
```

and fixed with this
```clojure
(defrecord ShellComponent [command]
  component/Lifecycle
  (start [this]
    (if-not (:running this)
      (do
        (println "Shell command:" (str/join " " command))
        (future (apply clojure.java.shell/sh command))))
    (assoc this :running true)))
```

Also by default lein-less try to find less files in `resources` dir
i fix this by adding this in project.clj
```clojure
:less {:source-paths ["src/less"]
         :target-path "resources/public/css"}
```

**Comment by plexus** [comment]
Thanks for the report, it'll be fixed ASAP.

**Comment by plexus** [comment]
The fixes are on master, you can try them out by following the instructions in the README for running a local install. I'll push them out later today or tomorrow.

**Comment by tkachenko1503** [comment]
@plexus thanks
