### ISSUE TITLE
Add support to ClojureScript browser repl, Chrome extension Dirac DevTools

### ISSUE THREAD

**Issue by stardiviner** [plexus/chestnut#201]
I'm a newbie on Clojure and ClojureScript, I don't know whether `figwheel` has support for Clojure Browser REPL (brepl). But I know I can't do `(require 'cljs.repl.browser)`, neither `(js/alert "hello")`.

Also I hope can integrate Chrome extension `Dirac DevTools`, It looks really great.
If maintainer has some reasons, please tell me. Thanks.

**Comment by plexus** [comment]
Follow the instructions in the README. You can switch to a Figwheel browser repl with `(go)` `(cljs-repl)`

**Comment by stardiviner** [comment]
I found I can execute code like `(js/alert "hello")`, but can't get completion with `CIDER`. How can I get completion in Emacs CIDER for bREPL?

**Comment by plexus** [comment]
Not sure if CIDER can do completion on cljs, but you can try using `cider-jack-in-clojurescript`.

**Comment by stardiviner** [comment]
After `cider-jack-in-clojurescript`, still does not work. I have posted an issue on `CIDER`.
