### ISSUE TITLE
Issue with dashes in project name

### ISSUE THREAD

**Issue by Peter-Donner** [plexus/chestnut#210]
A command like `lein new chestnut foo-bar` generates faulty code in index.html. 
`foo-bar.system.go();` instead of `foo_bar.system.go();` (underscore instead of minus).

Maybe using `{{sanitized}}` instead of `{{project-ns}}` in [index.html](https://github.com/plexus/chestnut/blob/9d46ee28e3f94a4c5ee6758b6382747d95c78019/src/leiningen/new/chestnut/resources/public/index.html#L11) would fix the issue.

**Comment by plexus** [comment]
Thanks for catching this Peter. Would you mind sending a pull request?
