### ISSUE TITLE
Run tests in auto mode?

### ISSUE THREAD

**Issue by jarednorman** [plexus/chestnut#221]
Maybe I've just missed something. From the README:

> Unit tests for both Clojure and CLJS. Both specs and CLJS tests can be run in "auto" mode.

I don't see any support for running tests in auto mode in my generated application. None of the plugins I know provide functionality like that are present. Did I miss something or is this claim stale?

**Comment by plexus** [comment]
For Clojure tests

```
lein auto test
```

For ClojureScript

```
lein doo phantom test
```

The second one is [mentioned in the docs](https://github.com/plexus/chestnut/blob/master/doc/02_02_testing.md), the first should be but isn't. A PR for that would be very appreciated.

Note that we only use GH issues for bug reports. For general questions it is recommended you use the [mailing list](http://clojureverse.org/c/chestnut). Thanks!
