### ISSUE TITLE
Figwheel version might need to be updated to latest

### ISSUE THREAD

**Issue by loganpowell** [plexus/chestnut#234]
- [x ] I am reporting a bug or problem in Chestnut

In reference to [an issue with clearing the browser cache between projects](https://github.com/bhauman/lein-figwheel/pull/586) I got on the #figwheel channel and found that older versions have this problem that I experienced where I used chestnut on two adjacent projects and the old project was loading in the browser.

**Comment by loganpowell** [comment]
Thank you @featheredtoast! Will do.

**Comment by plexus** [comment]
@featheredtoast I'm all for updating our dependencies, just been busy with other stuff. There's code in the repo to generate an up-to-date dependency list. If someone would like to prep a PR than I'll make sure it makes its way to Clojars.

**Comment by loganpowell** [comment]
Sorry, I've been on a project and doing this on the side, so just getting back to trying this, but got this:

```
Unrecognized option: +edge . Should be one of +http-kit +site-middleware +less +sass +reagent +vanilla +garden +rum +om-next +re-frame +code-of-conduct +coc +no-poll
```

**Comment by plexus** [comment]
ugh yeah we really need to get a new version out, seems the version on
clojars doesnt support edge yet. Meanwhile have a look at the README for
how to use the snapshot version. i think +edge should work with that.

**Comment by plexus** [comment]
Said new version is out now, all dependencies have been upgraded to latest, so a regular `lein new chestnut` should do the trick. Thanks for reporting this!

**Comment by loganpowell** [comment]
Sweet!! Thank you so much 👍
