### ISSUE TITLE
Unrecognized option: +bidi 

### ISSUE THREAD

**Issue by eallik** [plexus/chestnut#240]
```
$ lein new chestnut myproj --force --template-version 0.16.0 -- +re-frame +http-kit +bidi
...
Unrecognized option: +bidi
```

**Comment by plexus** [comment]
Bidi support isn't released yet. You can `git clone` Chestnut, then do `lein install` in the directory to get the latest master version.

**Comment by featheredtoast** [comment]
I've pushed a new template version with this and a few fixes - this should work now
