### ISSUE TITLE
Replace the Compojure middleware with ring-defaults

### ISSUE THREAD

**Issue by plexus** [plexus/chestnut#52]
The compojure.handler namespace will be deprecated in favor of ring-defaults (https://github.com/ring-clojure/ring-defaults)

It seems we can straightforwardly swap out one for the other.

**Comment by hellofunk** [comment]
when will this be released? my lein new chestnut .... still gives me the deprecated handler api

**Comment by hellofunk** [comment]
interestingly, i just did a lein new chestnut appname --snapshot and got the new ring defaults, but the dev.clj was not there! it referenced the dev namespace but did not include it anywhere in the project.

**Comment by plexus** [comment]
It's not under env?

**Comment by hellofunk** [comment]
oh that's interesting, it was moved to a different directory and no longer appears anywhere in the src/ directory. i didn't know source could live outside src/

**Comment by plexus** [comment]
You can set multiple source directories in project.clj. We use this
mechanism to load different files in development vs production. That way in
production there's no dependency on e.g. Figwheel.

**Comment by plexus** [comment]
You can help with #74 if you want to see this released.
