### ISSUE TITLE
Example of using externs to require an npm module

### ISSUE THREAD

**Issue by olivergeorge** [plexus/chestnut#68]
I think this should be easy but it's tripping me up.  

I think I should be able to "npm install jquery" and "npm install select2" and then follow David's advice:
http://swannodette.github.io/2014/03/14/externs-got-you-down/

Not having much luck at this stage... perhaps it's a good one to include as an example.

**Comment by RadicalZephyr** [comment]
It's probably better to build a [cljsjs](http://cljsjs.github.io/) package for select2 rather than trying to follow the advice on that blog page.  The process of packing up a javascript library really isn't too difficult.  I just did it for Waypoints.

**Comment by wilkerlucio** [comment]
I agree with @RadicalZephyr on that, cljsjs (foreign-libs) is the current best option for dealing with external libraries.

**Comment by slester** [comment]
It looks like [CLJSJS](http://cljsjs.github.io/) is the best route to this, and it's not really a Chestnut-specific issue, so I'll go ahead and close this issue.

**Comment by madbonkey** [comment]
Could this be reopened in light of the recent npm-related enhancements?
