### ISSUE TITLE
Add sass support with sass-clojure

### ISSUE THREAD

**Issue by plexus** [plexus/chestnut#70]
There was a previous attempt to support Sass using sassc, but installing the sassc binaries requires building libsass and sassc from source, which is not acceptable for Chestnut's target audience.

Using sass-clojure, we can simply rely on JRuby and use the canonical Ruby based implementation. All that's needed is for someone to write leiningen hooks to wire things up.

https://github.com/mylesmegyesi/sass-clojure

Previous discussion here: https://github.com/plexus/chestnut/issues/61

**Comment by bzalasky** [comment]
I'm interested in working on this. Still a bit new to Clojure, but I think I should be able to figure it out. Right now I'm using Sprockets-Standalone in a side project with Chestnut, but this is probably better for Chestnut moving forward. 

The one positive with Sprockets is that it takes care of mapping asset filenames to their fingerprinted counterparts for cache-busting. I don't think it would be terribly difficult to implement, but it would need to handle all asset types (images, js, css, etc..). Definitely beyond the scope of what this PR will be...

**Comment by plexus** [comment]
Thanks for your interest in helping out with this. The main missing piece is a leiningen plugin so we can easily hook sass compilation in. Looking at some of the existing plugins like line-auto, lein-cljx or lein-less should give you a good starting point.

I'm personally not a fan of Sprockets, I've had way too much pain dealing with Sprockets in Rails apps. There's a Clojure alternative, [Stefon](https://github.com/circleci/stefon), which looks promising (it's by CircleCI). But in general we're trying not to add more complexity to Chestnut. Testing all the different flags is already a massive chore.

Recipes in the docs for adding Stefon or Sprockets would be very cool though.

Anyway, good luck with this. Ping me if you like me to review any code.

**Comment by bzalasky** [comment]
Totally understand your thoughts on Sprockets. I have mixed feelings myself. All I'm using it for is generating asset fingerprints. I hope to replace it with something lighter-weight in the future.

**Comment by bzalasky** [comment]
Was going to start working on this today, but remembered that there is a [lein-haml-sass](https://github.com/rtircher/lein-haml-sass) plugin already. Is there a compelling reason not to use this? It's not been updated in awhile, but I can confirm that it still works. The only other knock is that it bundles Haml and Sass together, though it provides separate commands for each, and I'm not sure it's that big of a deal since it's just a dev dependency. It also supports both *.sass and *.scss.

If you think it's worth it, I'm still down for extracting the Sass functionality out and making sure it stays maintained.

**Comment by plexus** [comment]
That looks perfect! Would be happy to have that instead of the current
sassc stuff.

**Comment by plexus** [comment]
@bzalasky did you make any progress on this? Anything you would like help with?

**Comment by bzalasky** [comment]
I was a bit distracted the month of January, but put in some work tonight. Hopefully, can get to the point of having a good question to ask by the end of the weekend. Thanks for following up!

**Comment by bzalasky** [comment]
Got most of this done this weekend. Still need to debug a bit though, as things didn't seem to be working when I ran lein install and tested out the changes. Will work on it a bit more this evening.

**Comment by plexus** [comment]
cool!

**Comment by slester** [comment]
@bzalasky Any update with this? If you're not up for implementing it, I may give it a stab.

**Comment by bzalasky** [comment]
Sorry for dropping off the thread for a bit there (got super busy getting a product released). I ended up just handling this outside of Chestnut. Feel free to take a stab at it though.

**Comment by plexus** [comment]
I'm no longer convinced this is something we should have in chestnut as a flag. I'm leaning towards dropping less and sass support, and instead documenting how to add them yourself. that way we can also provide install instructions for libsass.
