### ISSUE TITLE
Errors in fresh project: in-seconds does not exist

### ISSUE THREAD

**Issue by mhuebert** [plexus/chestnut#8]
I'm trying out chestnut for the first time, and when I create a new chestnut project and enter (run) in a lein repl, I get the following:

`CompilerException java.lang.RuntimeException: Unable to resolve symbol: run in this context, compiling:(/private/var/folders/gk/bxgzz2tn5gs2249f05hkw2jh0000gn/T/form-init1377301235688307069.clj:1:1)`

Also, while the repl loads, I see this:

`#<CompilerException java.lang.IllegalAccessError: in-seconds does not exist, compiling:(ring/middleware/cookies.clj:1:1)>`

**Comment by hellofunk** [comment]
I am also having this same problem, but I am not using spyscope:

`CompilerException java.lang.RuntimeException: Unable to resolve symbol: run in this context, `

In my case, the error started when I made my ~/.lein/profiles.clj look like this: 

https://github.com/clojure-emacs/example-config/blob/master/profiles_sample.clj

I just added the `refactor-nrepl` and the errors started. Note that this profiles.clj example is an official recommendation from the clojure-emacs team.

My profiles.clj in .lein looks exactly like the sample.

**Comment by plexus** [comment]
Do you also get the `in-seconds` error?

Do a `lein deps :tree` and you should see which offender is pulling in the outdated `clj-time`. This really is an upstream issue. We can't guarantee compatibility with every lib out there, especially not for outdated versions.

**Comment by hellofunk** [comment]
I do not get an in-seconds error.

**Comment by plexus** [comment]
In that case your problem is probably unrelated to the one reported here. Anything that causes compilation or loading of `your-project.server` to fail would show the same symptom of `run` not being defined.

Do you see any other warnings or errors?

Could you please file a new issue? Include the link to your `profiles.clj`, the output of `lein clean ; lein repl`, and the version of chestnut you're using.

**Comment by mhuebert** [comment]
I can confirm that updating spyscope to 0.1.5 fixed my error. Thank you to all.
