### ISSUE TITLE
Figwheel (as of 0.2.2-SNAPSHOT) opens a REPL into a running app.

### ISSUE THREAD

**Issue by mudphone** [plexus/chestnut#80]
I wasn't sure where to open this discussion / comment. It looks like the latest Figwheel handles opening a REPL into your running app.

Here's a short announcement on this from the author:
https://twitter.com/bhauman/status/555842947250651138

I tested the REPL with CLJS 0.0-2665, which is required for it to work. Older versions of CLJS will hang the REPL.

Is this something that might be a good replacement for Weasel/Piggieback? Or, would this complement it, or neither?

**Comment by plexus** [comment]
Interesting! Something to keep an eye on at least. If it's not piggieback-based it might exclude CIDER/Cursive/Lightable users which is not something I'd want to do.

This is also interesting: https://github.com/bhauman/lein-figwheel#using-figwheel-from-the-repl 
Might allow us to stop shelling out to leiningen.

My time on Chestnut is a bit limited again at the moment, unfortunately.
