### ISSUE TITLE
cljs macro issue

### ISSUE THREAD

**Issue by improper** [plexus/chestnut#81]
I'm not sure who to turn to with this problem.

When trying to compile (`lein cljsbuild once`) this branch:

https://github.com/improper/clojexcms/tree/schema-demo

I get

`Caused by: clojure.lang.ExceptionInfo: java.lang.ExceptionInInitializerError, compiling:(schema/macros.clj:1:1) at line 1 file:/Users/improper/.m2/repository/prismatic/schema/0.3.1/schema-0.3.1.jar!/schema/core.cljs {:tag :cljs/analysis-error, :file "file:/Users/improper/.m2/repository/prismatic/schema/0.3.1/schema-0.3.1.jar!/schema/core.cljs", :line 1, :column 1}`

The error occurred after depending on om-bootstrap, which depends on schema 0.3.1. Using schema 0.3.3 directly yields the same error after requiring the macros.

cljsbuild runs fine when removing the dependency on leiningen (project.clj line 53) – of course this breaks the figwheel startup.

I tried to construct a minimal example to reproduce this incompatibility but to no avail, something in the chestnut template seems to trigger it.

#69 might solve this, but anyhow: WTF? Any help appreciated.

**Comment by improper** [comment]
At least a minimal example based on chestnut:

https://github.com/improper/chestnut-cljs-error

**Comment by plexus** [comment]
I tried your example app, I got an error though a different one than you posted.

Good thing you split up the repo in two commits (lein new vs actual changes), so I re-applied your changes on a lein new using current master, and it seems to work fine now.
