### ISSUE TITLE
Changes to index.html aren't picked up at reload

### ISSUE THREAD

**Issue by gphilipp** [plexus/chestnut#84]
Hi Arne, 

After creating a fresh new project from chestnut template, I start the server with (run).
I go to http://localhost:10555 and see Hello Chesnut.
Now if I add a simple ```<h1>FOO</h1>``` just before the ```<div id="app"></div>```, and hit refresh in the browser, nothing changes. I understand that saving the html files doesn't triggers a refresh, but reloading in the browser should work right ?

I tried this on Mac and Windows, and also tried with the snapshot version of Chestnut.

**Comment by martinklepsch** [comment]
As far as I understood this should work since #53.
You currently have to use the snapshot (0.7.0-SNAPSHOT) version of chestnut.

**Comment by gphilipp** [comment]
Ok, so it works ok with chestnut 0.7-0-SNAPSHOT on Mac, note that you have to wait for the "Reloading <your namespace> message to appear for the refresh action in the browser to be successful at showing the updates to the html file.

Now, it DOESN'T work on Windows, because there seems to be an issue with Enlive not recognising URLs with a colon in the path.

e.g
```(watch-url (java.net.URL. "file:/C:/Users/gphilip/dev/chestnut-newtest/resources/index.html")  "chestnut-newtest.server")``` 

fails with this error 

```InvalidPathException Illegal char <:> at index 2: /C:/Users/gphilip/dev/chestnut-newtest/resources/index.html  sun.nio.fs.WindowsPathParser.normalize (WindowsPathParser.java:182)```

/poke @cgrand :smile:

**Comment by plexus** [comment]
Yup, reported separately in #104 now. The upstream issue is https://github.com/cgrand/enlive/issues/92
