### ISSUE TITLE
Regression: Snapshot build displays ArityException on (browser-repl)

### ISSUE THREAD

**Issue by tuhlmann** [plexus/chestnut#85]
This seems to have resurfaced again in latest --snapshot builds.

I ran:

    lein new chestnut my-app --snapshot

The generated browser-repl code is:

    defn browser-repl []
      (let [repl-env (weasel/repl-env :ip "0.0.0.0" :port 9001)]
        (piggieback/cljs-repl :repl-env repl-env)
        (piggieback/cljs-eval repl-env '(in-ns 'my-app.core) {})))

The error is:

    ArityException Wrong number of args (2) passed to: repl/fn--5124/self--5130  clojure.lang.AFn.throwArity (AFn.java:429)

    
                      AFn.java:  429  clojure.lang.AFn/throwArity
                      AFn.java:   36  clojure.lang.AFn/invoke
                      AFn.java:  156  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  626  clojure.core/apply
                piggieback.clj:  106  cemerick.piggieback/cljs-eval/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  624  clojure.core/apply
                      core.clj: 1862  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
                piggieback.clj:   97  cemerick.piggieback/cljs-eval
                       dev.clj:   20  my-app.dev/browser-repl
                          REPL:    1  my-app.server/eval21308

**Comment by tuhlmann** [comment]
In order to make it work, I updated these dependencies:

     [com.cemerick/piggieback "0.1.5"]
     [weasel "0.5.0"]

and changed the cljs-eval call in dev.clj to:

    (piggieback/cljs-eval {} repl-env '(in-ns 'my-app.core) {})))

**Comment by samedhi** [comment]
This is using 0.7.0-SNAPSHOT...

tuhlmann meant 
````
(piggieback/cljs-eval {} repl-env '(in-ns 'my-app.core) {}) ;; no extra parens 
````
in APP_NAME/env/dev/clj/APP_NAME/dev.clj

Although now I always get the following.

````
; CIDER 0.9.0alpha (package: 20141227.1232) (Java 1.7.0_76, Clojure 1.6.0, nREPL 0.2.6)
forum5.server> (browser-repl)
<< started Weasel server on ws://0.0.0.0:9001 >>
Type `:cljs/quit` to stop the ClojureScript REPL
IOException No client connected to Websocket  weasel.repl.server/send! (server.clj:25)
forum5.server> 
````

Which is no biggy, just reload the browser. Though it seems a bit dumb because yeah, how could I have a connection, I just started the brower-repl, give me a second...

**Comment by plexus** [comment]
Is this an issue on current master? I've been testing it quite a bit the last few days and haven't seen this.
