### ISSUE TITLE
Where is react.js

### ISSUE THREAD

**Issue by hellofunk** [plexus/chestnut#88]
Hello,
Can you tell me how Chestnut gets the react.js file? I see there is a route specified for /react but I do not understand how that works, or where the actual js file is located.

**Comment by plexus** [comment]
Om depends on `com.facebook/react`, which includes it, and adds its location to the classpath.

The [chat room](https://gitter.im/plexus/chestnut) might be a better channel for these kind of questions :smile:

**Comment by hellofunk** [comment]
Thanks, cool I didn't know github had chat rooms!

**Comment by martinklepsch** [comment]
It should be noted that newer versions of Om (`0.8.4+`) no longer depend on `com.facebook/react` and instead uses `:foreign-libs` compatible jars which requires Clojurescript 0.0-2727 or above.

**Comment by plexus** [comment]
Right, thanks for pointing that out Martin :)

**Comment by plexus** [comment]
@hellofunk the chatrooms are by Gitter, it's not a service of Github but it integrates really nicely
