### ISSUE TITLE
How to deal with println in production

### ISSUE THREAD

**Issue by plexus** [plexus/chestnut#92]
Looking for some input on this. Currently in dev mode Chestnut calls [`(enable-console-print!)`](http://crossclj.info/fun/cljs.core.cljs/enable-console-print!.html), setting `*print-fn*`, so that a `println` does a `console.log`.

When running the app in production mode *print-fn* will not be set, and any lingering `println`s will cause an error.

I see three options

1) leave it as is, maybe add a faq entry. Those printlns shouldn't be in the code you deploy
2) add a `(def *print-fn* (fn [& args]))`, i.e. swallow the calls
3) always call `(enable-console-print!)`

Now taking votes and thoughtful arguments.

**Comment by samedhi** [comment]
I think I would lean towards 3. If it matters to you, you can always wrap your println in something that disables them during deployment. No solution seems clearly superior though.
