### ISSUE TITLE
Control over the server Figwheel

### ISSUE THREAD

**Issue by felipecc** [plexus/chestnut#98]
I've been trying to make some changes in Chestnut to use it with the Component Stuart Sierra (https://github.com/stuartsierra/component). I made the integration however, when I went to restart the application received an error message stating that the port was being used, I later found out was the Figwheel server that was still standing. Checking how the Figwheel was called arrived at the following function:

(defn start-figwheel []
  (future
    (print "Starting figwheel.\n")
    (lein/-main ["figwheel"])))

This is the same as typing figwheel law in the root of your project. Unfortunately there are several layers in the end does not return me the server. There is another way that I can call the Figwheel within the Chestnut and still have control over the server that is raising the Figwheel?

Many apologies for my bad English.

Many Thanks.

**Comment by plexus** [comment]
Hi @felipecc 

Have a look at the current master/snapshot versions of Chestnut. We dropped the dependency on leiningen. Figwheel is now invoked more directly by using figwheel-sidecar.

**Comment by plexus** [comment]
Will you be sharing notes on how to use the component approach with figwheel/chestnut? :)

**Comment by felipecc** [comment]
Of Course !!!
